# Generated by Django 3.1.7 on 2021-03-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='job', max_length=255, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('attackBonus', models.IntegerField(blank=True, null=True)),
                ('damageBonus', models.IntegerField(blank=True, null=True)),
                ('evadeBonus', models.IntegerField(blank=True, null=True)),
                ('hpBonus', models.IntegerField(blank=True, null=True)),
                ('spBonus', models.IntegerField(blank=True, null=True)),
                ('ac', models.IntegerField(blank=True, null=True)),
                ('startingHp', models.IntegerField(blank=True, null=True)),
                ('startingSp', models.IntegerField(blank=True, null=True)),
                ('magicUser', models.BooleanField(blank=True, default=False, null=True)),
                ('tank', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
