# Generated by Django 3.1.7 on 2021-03-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('desc', models.TextField(null=True)),
                ('north', models.IntegerField(null=True)),
                ('south', models.IntegerField(null=True)),
                ('east', models.IntegerField(null=True)),
                ('west', models.IntegerField(null=True)),
                ('up', models.IntegerField(null=True)),
                ('down', models.IntegerField(null=True)),
                ('lit', models.BooleanField(null=True)),
                ('area', models.CharField(max_length=255, null=True)),
                ('danger', models.BooleanField(null=True)),
                ('static', models.ImageField(null=True, upload_to='rooms/')),
                ('walk', models.ImageField(null=True, upload_to='rooms/')),
            ],
        ),
    ]
