# Generated by Django 3.1.7 on 2021-03-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20210323_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='static',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='walk',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
