# Generated by Django 3.1.7 on 2021-03-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20210326_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
