# Generated by Django 3.1.7 on 2021-03-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
