# Generated by Django 3.1.7 on 2021-03-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
