# Generated by Django 3.1.7 on 2021-03-08 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_auto_20210308_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='hpmax',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='job',
            field=models.CharField(choices=[('WA', 'Warrior'), ('MA', 'Magician')], default='WA', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='sp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spmax',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='xp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.weapon'),
        ),
    ]
