# Generated by Django 3.1.7 on 2021-03-08 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_auto_20210308_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='weapon',
        ),
    ]
