# Generated by Django 3.1.7 on 2021-03-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_remove_character_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ac',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='job',
            field=models.CharField(choices=[('Warrior', 'Warrior'), ('Magician', 'Magician')], default='Warrior', max_length=15, null=True),
        ),
    ]
