# Generated by Django 3.1.7 on 2021-03-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_character_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='attack',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='con',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='dex',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='int',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='str',
            field=models.IntegerField(null=True),
        ),
    ]
