# Generated by Django 3.1.7 on 2021-03-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_auto_20210316_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='lastRoom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
