# Generated by Django 3.1.7 on 2021-03-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_character_lastroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weapon',
        ),
    ]
