# Generated by Django 3.1.7 on 2021-03-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_auto_20210326_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='conBonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='dexBonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='intBonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='strBonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
