# Generated by Django 3.1.7 on 2021-03-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_auto_20210326_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='weaponInventory',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
