# Generated by Django 3.1.7 on 2021-03-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_character_weaponinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='inventory',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
