# Generated by Django 3.1.7 on 2021-03-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0015_character_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='inventory',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
