# Generated by Django 3.1.7 on 2021-03-27 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210327_0119'),
        ('characters', '0019_auto_20210327_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='equippedWeapon',
            field=models.ForeignKey(blank=True, default=dict, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
    ]
