# Generated by Django 3.1.7 on 2021-03-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0023_auto_20210328_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='equippedWeapon',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
