# Generated by Django 3.1.7 on 2021-03-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0028_auto_20210329_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='equippedWeapon',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='inventory',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
