# Generated by Django 3.1.7 on 2021-03-30 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0032_auto_20210329_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='equippedWeapon',
        ),
    ]
