# Generated by Django 3.1.7 on 2021-03-30 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_isusable'),
        ('characters', '0033_remove_character_equippedweapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='equippedWeapon',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
    ]
