# Generated by Django 3.1.7 on 2021-03-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0035_auto_20210330_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='equippedWeapon',
            field=models.JSONField(blank=True, default=[{'bonus': 0, 'damMessage': 'annoys', 'damageHigh': 2, 'damageLow': 1, 'desc': 'A crummy little letter opener', 'id': 2, 'isMoney': 'false', 'isUsable': 'false', 'isWeapon': 'true', 'level': 1, 'makesLight': 'false', 'material': 'Bronze', 'name': 'letter opener', 'range': 'null', 'type': 'Knife', 'value': 1}], null=True),
        ),
    ]
