# Generated by Django 3.1.7 on 2021-03-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0036_auto_20210330_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='equippedWeapon',
            field=models.JSONField(blank=True, default=[{'bonus': 0, 'damMessage': 'annoys', 'damageHigh': 2, 'damageLow': 1, 'desc': 'A crummy little letter opener', 'id': 2, 'isMoney': False, 'isUsable': False, 'isWeapon': True, 'level': 1, 'makesLight': False, 'material': 'Bronze', 'name': 'letter opener', 'range': '', 'type': 'Knife', 'value': 1}], null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='inventory',
            field=models.JSONField(blank=True, default=[{'bonus': 0, 'damMessage': 'singes', 'damageHigh': None, 'damageLow': None, 'desc': 'A rag on a stick.', 'id': 4, 'isMoney': False, 'isUsable': True, 'isWeapon': False, 'level': 1, 'makesLight': True, 'material': 'Wood', 'name': 'torch', 'range': None, 'type': 'Misc', 'value': 2}, {'bonus': 0, 'damMessage': 'bruises', 'damageHigh': 2, 'damageLow': 1, 'desc': 'A blunt wooden sword for children. Good luck saving the world, hero.', 'id': 3, 'isMoney': False, 'isUsable': False, 'isWeapon': True, 'level': 1, 'makesLight': False, 'material': 'Wood', 'name': 'practice sword', 'range': None, 'type': 'Sword', 'value': 1}], null=True),
        ),
    ]
