# Generated by Django 3.1.7 on 2021-03-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0037_auto_20210330_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='builder',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
