# Generated by Django 3.1.7 on 2021-03-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0039_character_jobchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='magicUser',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
