# Generated by Django 3.1.7 on 2021-03-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0040_character_magicuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='jobchoice',
            field=models.CharField(default='Fighter', max_length=255, null=True),
        ),
    ]
