# Generated by Django 3.1.7 on 2021-03-30 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0041_auto_20210330_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='job',
        ),
    ]
