# Generated by Django 3.1.7 on 2021-03-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0042_remove_character_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='jobchoice',
        ),
        migrations.AddField(
            model_name='character',
            name='job',
            field=models.CharField(default='Warrior', max_length=255, null=True),
        ),
    ]
