# Generated by Django 3.1.7 on 2021-03-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('damageLow', models.IntegerField(blank=True, null=True)),
                ('damageHigh', models.IntegerField(blank=True, null=True)),
                ('spCost', models.IntegerField(blank=True, null=True)),
                ('damMessage', models.CharField(max_length=255, null=True)),
                ('element', models.CharField(blank=True, choices=[('None', 'None'), ('Electricity', 'Electricity'), ('Fire', 'Fire'), ('Water', 'Water'), ('Earth', 'Earth'), ('Force', 'Force'), ('Silver', 'Silver'), ('Antimagic', 'Antimagic'), ('Acid', 'Acid')], default='None', max_length=15, null=True)),
            ],
        ),
    ]
