# Generated by Django 3.1.7 on 2021-03-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='combat',
            field=models.BooleanField(null=True),
        ),
    ]
