# Generated by Django 3.1.7 on 2021-03-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='item', max_length=255, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, default=1, null=True)),
                ('makesLight', models.BooleanField(blank=True, default=False, null=True)),
                ('money', models.BooleanField(blank=True, default=False, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
