# Generated by Django 3.1.7 on 2021-03-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='weakness',
            field=models.CharField(choices=[('None', 'None'), ('Fire', 'Fire'), ('Water', 'Water'), ('Earth', 'Earth'), ('Force', 'Force'), ('Silver', 'Silver'), ('Antimagic', 'Antimagic'), ('Acid', 'Acid')], default='None', max_length=15, null=True),
        ),
    ]
