# Generated by Django 3.1.7 on 2021-03-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobs', '0002_mob_weakness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mob',
            name='weakness',
            field=models.CharField(choices=[('None', 'None'), ('Electricity', 'Electricity'), ('Fire', 'Fire'), ('Water', 'Water'), ('Earth', 'Earth'), ('Force', 'Force'), ('Silver', 'Silver'), ('Antimagic', 'Antimagic'), ('Acid', 'Acid')], default='None', max_length=15, null=True),
        ),
    ]
