# Generated by Django 3.1.7 on 2021-03-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobs', '0003_auto_20210323_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='inventory',
            field=models.JSONField(default=[], null=True),
        ),
    ]
