# Generated by Django 3.1.7 on 2021-03-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobs', '0004_mob_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mob',
            name='inventory',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
