# Generated by Django 3.1.7 on 2021-03-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobs', '0005_auto_20210326_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='isShopkeeper',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
