# Generated by Django 3.1.7 on 2021-03-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobs', '0006_mob_isshopkeeper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mob',
            name='ac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mob',
            name='attack',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mob',
            name='damMessage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mob',
            name='damage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mob',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mob',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mobs/'),
        ),
        migrations.AlterField(
            model_name='mob',
            name='inventory',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='mob',
            name='sp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mob',
            name='spmax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mob',
            name='weapon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mob',
            name='xp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
