# Generated by Django 3.1.7 on 2021-03-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobs', '0007_auto_20210327_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='silver',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
